
#------------------------------------------------------------------------------
# Py2C - A Python to C++ compiler
# Copyright (C) 2014 Pradyun S. Gedam
#------------------------------------------------------------------------------

language: python
python:
  - 3.3
  - 3.4

install:
  # Install/Upgrade Dependencies (NOTE: Doesn't use mock, at least not now)
  - pip install -U nose mock coverage coveralls

  # Auto-generate AST files
  - pip install ply
  - python setup.py build_py

  - python setup.py develop

script:
  # Run the tests
  - python .dev_tools/run_tests.py

after_success:
  - coveralls --rcfile=.dev_tools/.coveragerc
