# Basic information
title: Py2C
tagline: 'A Python to C++ translator'
description: 'A trans-compiler for compiling Python code into human-readable C++ code, somewhat like what humans might actually write.'

base_url: http://pradyun.github.io/Py2C

author:
  name: Pradyun Gedam
  url: https://github.com/pradyun

github:
  repo: https://github.com/pradyun/Py2C
version: pre-alpha

# Permalinks
permalink: pretty
relative_permalinks: true

# Dependencies
markdown: redcarpet
highlighter: pygments
